package Consultas;


import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.GroupLayout.Alignment;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;

import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import com.toedter.calendar.JDateChooser;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;

@SuppressWarnings("serial")
public class Visual extends javax.swing.JFrame {

	Tabla_DatosPersona t = new Tabla_DatosPersona();

	JButton btnBuscar = new JButton("Buscar");
	JLabel lblLegajo = new JLabel("Legajo:");	
	JLabel lblNombre = new JLabel();
	JDateChooser desdeBoton = new JDateChooser();
	JDateChooser hastaBoton = new JDateChooser();
	JLabel datosEmpresa = new JLabel();
	Impresion impresion1 = new Impresion();
	
	Limpiar_Caja lim = new Limpiar_Caja();

	Metodos met;

	int clic_tabla = 0;

	public Visual() {
		initComponents();  
		activa_boton(true,false,false);
	}

	//Metodo agregar producto
	public void agregar(){
		met = new Metodos();
		DatosPersona dp = new DatosPersona();
		try {
			dp.setIdLegajo(Integer.parseInt(txtIdLegajo.getText()));
			dp.setMomentoMarcacion(txtMomentoMarcacion.getText());
			if(comboBox.getSelectedItem() == "Ingreso") {
				dp.setIdTipoMarca(1);
			}
			if(comboBox.getSelectedItem() == "Egreso") {
				dp.setIdTipoMarca(2);
			}
			if(comboBox.getSelectedItem() == "Salida Almuerzo") {
				dp.setIdTipoMarca(3);
			}
			if(comboBox.getSelectedItem() == "Retorno Almuerzo") {
				dp.setIdTipoMarca(4);
			}
			
			met.Agregar_DatosPersona(dp, comboBox, datosEmpresa);
		} catch(Exception e) {
			JOptionPane.showMessageDialog(null, "Error. Momento de Marcacion o tipo de Marca invalido");
		}
	}

	//Metodo modificar producto
	public void modificar(){
		met = new Metodos();
		DatosPersona dp = new DatosPersona();

		dp.setIdLegajo(Integer.parseInt(txtIdLegajo.getText()));
		dp.setMomentoMarcacion(txtMomentoMarcacion.getText());
		comboBox.setSelectedItem((String)comboBox.getSelectedItem());
		dp.setId(Integer.parseInt(txtId.getText()));

		met.Modificar_DatosPersona(dp, comboBox);
	}

	//Metodo eliminar producto
	public void eliminar(){
		met = new Metodos();
		DatosPersona dp = new DatosPersona();

		dp.setId(Integer.parseInt(txtId.getText()));

		met.Eliminar_DatosPersona(dp);
	}

	public void activa_boton(boolean a1, boolean a2, boolean a3){
		btnAgregar.setEnabled(a1);
		btnModificar.setEnabled(a2);
		btnEliminar.setEnabled(a3);
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked

		clic_tabla = this.tabla.rowAtPoint(evt.getPoint());

		int id = (int)tabla.getValueAt(clic_tabla, 0);
		int idLegajo = (int) tabla.getValueAt(clic_tabla, 1);
		String momentoMarcacion = (String) tabla.getValueAt(clic_tabla, 2);
		Object idTipoMarca = (String) tabla.getValueAt(clic_tabla, 3);

		txtId.setText(String.valueOf(id));
		txtIdLegajo.setText(String.valueOf(idLegajo));
		txtMomentoMarcacion.setText(momentoMarcacion);
		comboBox.setSelectedItem(idTipoMarca);
		if(idTipoMarca.equals("Ingreso")) {
			comboBox.setSelectedItem("INGRESO");
		}
		else if(idTipoMarca.equals("Egreso")) {
			comboBox.setSelectedItem("EGRESO");
		}
		else if(idTipoMarca.equals("Salida Almuerzo")) {
			comboBox.setSelectedItem("SALIDA ALMUERZO");
		}
		else if(idTipoMarca.equals("Retorno Almuerzo")) {
			comboBox.setSelectedItem("RETORNO ALMUERZO");
		}

		int column = tabla.getColumnModel().getColumnIndexAtX(evt.getX());
		int row = evt.getY()/tabla.getRowHeight();

		if(row < tabla.getRowCount() && row >= 0 && column < tabla.getColumnCount() && column >= 0){
			Object value = tabla.getValueAt(row, column);
			if(value instanceof JButton){
				((JButton)value).doClick();
				JButton boton = (JButton) value;

				if(boton.getName().equals("m")){
					System.out.println("Click en el boton modificar");
					activa_boton(false,true,false);
				}
				if(boton.getName().equals("e")){
					System.out.println("Click en el boton eliminar");
					activa_boton(false,false,true);
				}
			}

		}

	}//GEN-LAST:event_tablaMouseClicked
	
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		tabla = new javax.swing.JTable();
		panel = new javax.swing.JPanel();
		btnAgregar = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		txtMomentoMarcacion = new javax.swing.JTextField();
		txtIdLegajo = new javax.swing.JTextField();
		txtId = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		btnModificar = new javax.swing.JButton();
		btnEliminar = new javax.swing.JButton();
		btnBuscar = new javax.swing.JButton("BUSCAR");
		jButton1 = new javax.swing.JButton();
		nrolegajo = new JTextField(10);
		btnAceptar = new JButton("ACEPTAR");
		comboBox = new JComboBox<String>();

		setIconImage(Toolkit.getDefaultToolkit().getImage(Visual.class.getResource("/Marcacion/logodatamex.jpg")));
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Consulta");

		tabla.setModel(new DefaultTableModel(
				new Object[][] {
				},
				new String[] {
						"Id", "Legajo", "Momento de Marcacion", "Tipo de Marca", "Modificar", "Eliminar"
				}
				));
		tabla.getColumnModel().getColumn(0).setPreferredWidth(50);
		tabla.getColumnModel().getColumn(1).setPreferredWidth(50);
		tabla.getColumnModel().getColumn(2).setPreferredWidth(150);
		tabla.getColumnModel().getColumn(3).setPreferredWidth(50);
		tabla.setRowHeight(20);

		tabla.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				tablaMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(tabla);

		btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		btnAgregar.setText("Agregar");
		btnAgregar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAgregarActionPerformed(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel4.setText("Tipo de Marca:");

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel3.setText("Momento de Marcacion:");

		txtIdLegajo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtIdLegajoActionPerformed(evt);
			}
		});

		txtId.setEditable(false);
		txtIdLegajo.setEditable(false);

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel1.setText("Id:");

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel2.setText("Legajo:");

		btnBuscar.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				Tabla_DatosPersona.buscarLegajo(nrolegajo, lblNombre);
				Metodos.datosEmpresa(datosEmpresa, nrolegajo);
			}
		});

		btnAceptar.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				t.visualizar_DatosPersona(tabla, nrolegajo, desdeBoton, hastaBoton, comboBox);
				//lim.limpiar_texto(panel, desdeBoton, hastaBoton, comboBox, nrolegajo, lblNombre, tabla);
			}
		});

		desdeBoton.getCalendarButton().addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {

			}
		});

		hastaBoton.getCalendarButton().addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {

			}
		});


		btnModificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		btnModificar.setText("Modificar");
		btnModificar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnModificarActionPerformed(evt);
			}
		});

		btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		btnEliminar.setText("Eliminar");
		btnEliminar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnEliminarActionPerformed(evt);
			}
		});



		jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jButton1.setText("Limpiar");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
		panelLayout.setHorizontalGroup(
				panelLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(panelLayout.createSequentialGroup()
						.addContainerGap()
						.addGroup(panelLayout.createParallelGroup(Alignment.LEADING)
								.addGroup(panelLayout.createSequentialGroup()
										.addGroup(panelLayout.createParallelGroup(Alignment.LEADING)
												.addComponent(jLabel3)
												.addComponent(jLabel4))
										.addGap(26)
										.addGroup(panelLayout.createParallelGroup(Alignment.LEADING, false)
												.addComponent(comboBox, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(txtMomentoMarcacion, GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
										.addGap(3))
								.addGroup(panelLayout.createSequentialGroup()
										.addGroup(panelLayout.createParallelGroup(Alignment.LEADING)
												.addComponent(jLabel1)
												.addComponent(jLabel2))
										.addGap(18)
										.addGroup(panelLayout.createParallelGroup(Alignment.LEADING)
												.addComponent(txtId, GroupLayout.PREFERRED_SIZE, 196, GroupLayout.PREFERRED_SIZE)
												.addComponent(txtIdLegajo, 277, 277, 277)))
								.addGroup(panelLayout.createSequentialGroup()
										.addComponent(btnAgregar)
										.addPreferredGap(ComponentPlacement.UNRELATED)
										.addComponent(btnModificar)
										.addPreferredGap(ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
										.addComponent(btnEliminar)
										.addPreferredGap(ComponentPlacement.UNRELATED)
										.addComponent(jButton1)))
						.addContainerGap())
				);
		panelLayout.setVerticalGroup(
				panelLayout.createParallelGroup(Alignment.TRAILING)
				.addGroup(panelLayout.createSequentialGroup()
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(panelLayout.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel1)
								.addComponent(txtId, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(18)
						.addGroup(panelLayout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel2)
								.addComponent(txtIdLegajo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(18)
						.addGroup(panelLayout.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel3)
								.addComponent(txtMomentoMarcacion, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(18)
						.addGroup(panelLayout.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel4)
								.addComponent(comboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.RELATED)
						.addGroup(panelLayout.createParallelGroup(Alignment.BASELINE)
								.addComponent(btnAgregar)
								.addComponent(btnModificar)
								.addComponent(btnEliminar)
								.addComponent(jButton1))
						.addContainerGap())
				);
		panel.setLayout(panelLayout);
		
		btnImprimir = new JButton("IMPRIMIR");
		btnImprimir.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				PrinterJob job = PrinterJob.getPrinterJob();
				job.setPrintable(impresion1);
				
				if(job.printDialog()) {
					try {
						job.print();
					}catch(PrinterException e) {
						
					}
				}else {
					JOptionPane.showMessageDialog(null, "Impresion cancelada");
				}
			}
		});



		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
					.addGap(18)
					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
						.addComponent(panel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addGroup(layout.createSequentialGroup()
							.addGap(15)
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
									.addComponent(desdeBoton, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
									.addGap(18)
									.addComponent(hastaBoton, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
									.addGap(26)
									.addComponent(btnAceptar))
								.addGroup(layout.createSequentialGroup()
									.addComponent(lblLegajo, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(ComponentPlacement.UNRELATED)
									.addComponent(nrolegajo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
									.addComponent(btnBuscar, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
									.addGap(18)
									.addComponent(btnImprimir, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup()
									.addGap(10)
									.addComponent(lblNombre, GroupLayout.PREFERRED_SIZE, 208, GroupLayout.PREFERRED_SIZE)))))
					.addGap(55))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
					.addGap(14)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 275, GroupLayout.PREFERRED_SIZE)
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(lblLegajo)
								.addComponent(btnImprimir, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
								.addComponent(btnBuscar)
								.addComponent(nrolegajo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addGap(7)
							.addComponent(lblNombre)
							.addGap(13)
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addComponent(desdeBoton, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(btnAceptar)
								.addComponent(hastaBoton, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(panel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		getContentPane().setLayout(layout);

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void txtIdLegajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdLegajoActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_txtIdLegajoActionPerformed

	private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
		agregar();
		t.visualizar_DatosPersona(tabla, nrolegajo, desdeBoton, hastaBoton, comboBox);
		activa_boton(true,false,false);
		lim.limpiar_texto(panel, desdeBoton, hastaBoton, comboBox, nrolegajo, lblNombre, tabla);
	}//GEN-LAST:event_btnAgregarActionPerformed

	private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
		modificar();
		t.visualizar_DatosPersona(tabla, nrolegajo, desdeBoton, hastaBoton, comboBox);
		activa_boton(true,false,false);
		lim.limpiar_texto(panel, desdeBoton, hastaBoton, comboBox, nrolegajo, lblNombre, tabla);
	}//GEN-LAST:event_btnModificarActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		lim.limpiar_texto(panel, desdeBoton, hastaBoton, comboBox, nrolegajo, lblNombre, tabla);
		activa_boton(true,false,false);
	}//GEN-LAST:event_jButton1ActionPerformed

	private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

		int s = JOptionPane.showConfirmDialog(null, "Estas seguro que desea eliminar el registro?","Si/no", JOptionPane.WARNING_MESSAGE);//, JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION
		if(s == 0){
			eliminar();
			t.visualizar_DatosPersona(tabla, nrolegajo, desdeBoton, hastaBoton, comboBox);
			activa_boton(true,false,false);
			lim.limpiar_texto(panel, desdeBoton, hastaBoton, comboBox, nrolegajo, lblNombre, tabla);
		}

	}//GEN-LAST:event_btnEliminarActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {

		/* Set the Nimbus look and feel 
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {

			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}

		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		//Create and display the form 
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new Visual().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAgregar;
	private javax.swing.JButton btnEliminar;
	private javax.swing.JButton btnModificar;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JPanel panel;
	private javax.swing.JTable tabla;
	private javax.swing.JTextField txtId;
	private javax.swing.JTextField txtIdLegajo;
	private javax.swing.JTextField txtMomentoMarcacion;
	private JTextField nrolegajo;
	private JButton btnAceptar;
	private JComboBox<String> comboBox;
	private JButton btnImprimir;
}
